# Generated by Django 5.1 on 2024-08-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_iso_number_product_size_product_size_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
