# Generated by Django 5.1 on 2024-09-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_thanks_mini_text_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='iso_number',
            field=models.CharField(max_length=100),
        ),
    ]
