# Generated by Django 5.1 on 2024-09-09 08:05

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_image',
            field=models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator]),
        ),
    ]
