# Generated by Django 5.1 on 2024-09-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_image_alter_product_size_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sum_five_product',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sum_one_product',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
