# Generated by Django 5.1 on 2024-09-09 08:05

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_about_image_alter_carousel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator]),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to=main.validators.custom_file_path, validators=[main.validators.img_validator]),
        ),
    ]
